name: linux-mac-mpi-nceplibs
on: [push, pull_request]

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  matrix-build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-9
      FC: gfortran-9
      CXX: g++-9
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
        compiler: [gcc-9]
        mpi_type: [mpich, openmpi]
        netcdf_version: [4.9.0]

    steps:
    - name: install-dependencies
      run: |
        if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
          sudo apt-get update
          sudo apt-get install libpng-dev libjpeg-dev
          if [[ ${{ matrix.mpi_type}} == "mpich" ]]; then
             sudo apt-get install mpich      
          elif [[ ${{ matrix.mpi_type }} == "openmpi" ]]; then
             sudo apt-get install openmpi-bin
          fi
        elif [[ ${{ matrix.os }} == "macos-10.15" ]]; then
            brew update
          brew install wget
          if [[ ${{ matrix.mpi_type}} == "mpich" ]]; then
             brew install mpich      
          elif [[ ${{ matrix.mpi_type }} == "openmpi" ]]; then
             brew install open-mpi
          fi
          if [[ ${{ matrix.compiler }} == "gcc-9" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          elif  [[ ${{ matrix.compiler }} == "gcc-10" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
          fi
        fi
        python3 -m pip install gcovr

    - name: cache-netcdf
      id: cache-netcdf
      uses: actions/cache@v2
      with:
        path: ~/netcdf
        key: netcdf-c-${{ matrix.netcdf_version }}-${{ runner.os }}-${{ matrix.mpi_type }}3

    - name: build-hdf5
      if: steps.cache-netcdf.outputs.cache-hit != 'true'
      run: |
        export CC=mpicc
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.2/src/hdf5-1.12.2.tar.gz &> /dev/null
        tar -xzf hdf5-1.12.2.tar.gz
        pushd hdf5-1.12.2
        ./configure --prefix=${HOME}/netcdf --enable-parallel --disable-tools --disable-fortran --disable-cxx
        make -j2
        make install

    - name: Look at config.log if error
      shell: bash -l {0}
      run: cat config.log
      if: ${{ failure() }}
           
    - name: build-netcdf-c
      if: steps.cache-netcdf.outputs.cache-hit != 'true'
      run: |
        export CC=mpicc
        export CPPFLAGS=-I${HOME}/netcdf/include
        export LDFLAGS=-L${HOME}/netcdf/lib
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v${{ matrix.netcdf_version }}.tar.gz &> /dev/null
        tar -xzf v${{ matrix.netcdf_version }}.tar.gz
        cd netcdf-c-${{ matrix.netcdf_version }}
        ./configure --prefix=${HOME}/netcdf --disable-dap --disable-utilities 
        make -j2
        make install

    - name: Look at config.log if error
      shell: bash -l {0}
      run: cat config.log
      if: ${{ failure() }}
           
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        export CC=mpicc        
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH='~/netcdf'

      
